spring:
  application:
    name: tour-service
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 20
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      separator: ;;

tour-api:
  key: ${TOUR_API_KEY}
  url: ${TOUR_API_URL}

chat-service:
  url: http://chat-service-aws
